// Public surface of the Taxation frontend module: the ONLY import path other parts of the app may use.
export { default as OverviewTab } from './pages/OverviewTab.jsx'
export { default as BasTab } from './pages/BasTab.jsx'
export { default as TaxesTab, LEGACY as TAXES_LEGACY, SECTIONS as TAXES_SECTIONS, visibleSections as taxesVisibleSections } from './pages/TaxesTab.jsx'
export { default as ReturnsTab } from './pages/ReturnsTab.jsx'
export { default as IncomeTab } from './pages/IncomeTab.jsx'
export { default as CgtTab } from './pages/CgtTab.jsx'
export { default as FbtTab } from './pages/FbtTab.jsx'
export { default as PlanningTab } from './pages/PlanningTab.jsx'
export { default as CalendarTab } from './pages/CalendarTab.jsx'
export { default as WorkpapersTab } from './pages/WorkpapersTab.jsx'
export { default as ReportsTab } from './pages/ReportsTab.jsx'
export { default as LodgementTab } from './pages/LodgementTab.jsx'
export { default as SettingsTab } from './pages/SettingsTab.jsx'
export { default as AuditTab } from './pages/AuditTab.jsx'
export { me as taxMe } from './lib/taxApi.js'
export { default as SendDisposalsToTax } from './components/SendDisposalsToTax.jsx'
export { default as SendCryptoTradesToTax } from './components/SendCryptoTradesToTax.jsx'
