// Accounting: general-ledger API client (accounts, journals, drafts, FX, AI assistant). Uses the org-aware platform HTTP client.
import { http } from '../../../core/lib/platformHttp.js'

// ledger
export const accounts      = (include_inactive = false) => http.get('/ledger/accounts', { params: { include_inactive } })
export const createAccount = (b) => http.post('/ledger/accounts', b)
export const updateAccount = (id, b) => http.patch(`/ledger/accounts/${id}`, b)
export const accountTypes  = () => http.get('/ledger/account-types')
export const taxCodes      = () => http.get('/ledger/tax-codes')
export const tracking      = () => http.get('/ledger/tracking-categories')
export const addTracking   = (name) => http.post('/ledger/tracking-categories', { name })
export const addTrackingOpt= (id, name) => http.post(`/ledger/tracking-categories/${id}/options`, { name })
export const journals      = (params) => http.get('/ledger/journals', { params })
export const journal       = (id) => http.get(`/ledger/journals/${id}`)
export const postJournal   = (b) => http.post('/ledger/journals', b)
export const reverseJournal= (id, b = {}) => http.post(`/ledger/journals/${id}/reverse`, b)
export const syncBank      = (dry_run) => http.post('/ledger/sync/bank-transactions', null, { params: { dry_run } })
export const trialBalance  = (as_at) => http.get('/ledger/reports/trial-balance', { params: { as_at } })
export const profitLoss    = (from, to) => http.get('/ledger/reports/profit-loss', { params: { from, to } })
export const balanceSheet  = (as_at) => http.get('/ledger/reports/balance-sheet', { params: { as_at } })
export const generalLedger = (account_id, from, to) => http.get('/ledger/reports/general-ledger', { params: { account_id, from, to } })

// ── Journal workflow: preview, drafts + approval, AI suggestions, repeating, import, health ──
export const journalPreview   = (b) => http.post('/ledger/journal-preview', b)
export const journalSources   = () => http.get('/ledger/journal-sources')
export const journalHistory   = (id) => http.get(`/ledger/journals/${id}/history`)
export const journalSettings  = () => http.get('/ledger/journal-settings')
export const saveJournalSettings = (b) => http.put('/ledger/journal-settings', b)
export const ledgerHealth     = () => http.get('/ledger/ledger-health')
export const journalDrafts    = (params) => http.get('/ledger/journal-drafts', { params })
export const journalDraft     = (id) => http.get(`/ledger/journal-drafts/${id}`)
export const createDraft      = (b, submit = false) => http.post('/ledger/journal-drafts', b, { params: { submit } })
export const updateDraft      = (id, b) => http.put(`/ledger/journal-drafts/${id}`, b)
export const deleteDraft      = (id) => http.delete(`/ledger/journal-drafts/${id}`)
export const submitDraft      = (id) => http.post(`/ledger/journal-drafts/${id}/submit`)
export const approveDraft     = (id, b = {}) => http.post(`/ledger/journal-drafts/${id}/approve`, b)
export const rejectDraft      = (id, reason) => http.post(`/ledger/journal-drafts/${id}/reject`, { reason })
export const bulkApprove      = (min_confidence, ids) => http.post('/ledger/journal-drafts/bulk-approve', { min_confidence, ids })
export const generateSuggestions = () => http.post('/ledger/journal-suggestions/generate')
export const repeatingJournals = () => http.get('/ledger/repeating-journals')
export const createRepeating  = (b) => http.post('/ledger/repeating-journals', b)
export const updateRepeating  = (id, b) => http.put(`/ledger/repeating-journals/${id}`, b)
export const deleteRepeating  = (id) => http.delete(`/ledger/repeating-journals/${id}`)
export const runRepeating     = (as_at) => http.post('/ledger/repeating-journals/run', { as_at })
export const importJournals   = (b) => http.post('/ledger/journal-import', b)
export const importTemplateUrl = '/api/ledger/journal-import/template'
export const downloadImportTemplate = async () => {
  const r = await http.get('/ledger/journal-import/template', { responseType: 'blob' })
  const a = document.createElement('a'); a.href = URL.createObjectURL(r.data); a.download = 'journal-import-template.csv'; a.click()
}
export const fxRates          = (currency) => http.get('/ledger/fx-rates', { params: { currency } })
export const putFxRate        = (b) => http.put('/ledger/fx-rates', b)
export const deleteFxRate     = (id) => http.delete(`/ledger/fx-rates/${id}`)
export const fxRate           = (currency, date) => http.get('/ledger/fx-rate', { params: { currency, date } })
export const schedulerStatus  = () => http.get('/ledger/scheduler-status')
export const fxAccounts       = () => http.get('/ledger/fx/accounts')
export const setFxAccount     = (id, currency) => http.put(`/ledger/fx/accounts/${id}`, { currency: currency || null })
export const fxRevaluation    = (as_at) => http.get('/ledger/fx/revaluation', { params: { as_at } })
export const fxRevalue        = (b) => http.post('/ledger/fx/revalue', b)
export const fxGainsLosses    = (from, to) => http.get('/ledger/reports/fx-gains-losses', { params: { from, to } })
export const fxFeed           = () => http.get('/ledger/fx-feed')
export const fxFeedRun        = (b) => http.post('/ledger/fx-feed/run', b || {})
export const aiJournal        = (b) => http.post('/ledger/ai/journal-from-text', b)
export const aiReviewDraft    = (id) => http.post(`/ledger/ai/review-draft/${id}`)
export const aiExplainPL      = (b) => http.post('/ledger/ai/explain-profit-loss', b)
