"""Single Touch Payroll STRUCTURES: pay events, finalisation declarations and payment-summary data built from finalised pay runs.
IMPORTANT: AccFino does not lodge with the ATO. 'Mock submit' only records a reference so the workflow can be tested; the payload follows STP Phase 2 / Payday Super
concepts (qualifying earnings and super liability) but is NOT an ATO-certified file. TFNs are never written into stored payloads."""
from datetime import date, datetime
from decimal import Decimal
from typing import Optional
import uuid

from accfino.modules.payroll.models.payroll import PayEmployee, PayRun, PayRunEmployee, PayRunLine, PayStpEvent, PayStpFinalisation
from accfino.modules.payroll.services import audit, runbuild
from accfino.modules.payroll.services.errors import Conflict, NotFound, PayrollError
from accfino.modules.payroll.services.setup import get_settings

Z = Decimal(0)
S = lambda v: str(v if v is not None else 0)


def _employer(db, ctx):
    st = get_settings(db, ctx.org)
    return {"abn": st.abn or ctx.org.abn, "name": st.employer_name or ctx.org.name, "bms_id": (st.stp_config or {}).get("bms_id"), "branch_code": (st.stp_config or {}).get("branch_code")}


def pay_event_payload(db, ctx, run: PayRun, event_type="pay_event") -> dict:
    emps = []
    for re_ in db.query(PayRunEmployee).filter_by(run_id=run.id, status="included").order_by(PayRunEmployee.employee_number):
        lines = db.query(PayRunLine).filter_by(run_employee_id=re_.id).all()
        k = lambda *kinds: sum((l.amount for l in lines if l.kind in kinds), Z)
        y = re_.ytd or {}
        emps.append({"payee_ref": re_.employee_number, "name": re_.employee_name, "income_stream_type": "SAW",
                     "this_pay": {"gross": S(re_.gross), "paygw": S(re_.payg), "study_loan": S(re_.study_loan), "allowances": S(k("allowance")), "bonuses_commissions": S(k("bonus", "commission")),
                                  "leave_paid": S(k("leave", "leave_loading")), "unused_leave_termination": S(k("termination_leave")), "etp": S(k("etp")),
                                  "salary_sacrifice_super_resc": S(re_.sacrifice_super), "deductions": S(re_.posttax_deductions + re_.pretax_deductions),
                                  "qualifying_earnings": S(re_.qualifying_earnings), "super_liability": S(re_.super_guarantee)},
                     "ytd": {"gross": y.get("gross"), "paygw": y.get("tax"), "qualifying_earnings": y.get("qualifying_earnings"), "super_liability": y.get("super_guarantee"),
                             "resc": y.get("salary_sacrifice")}})
    return {"event_type": event_type, "software": "AccFino", "employer": _employer(db, ctx), "payroll_period": {"start": run.period_start.isoformat(), "end": run.period_end.isoformat()},
            "pay_date": run.pay_date.isoformat(), "run_no": run.run_no, "employees": emps,
            "totals": {"gross": S(run.total_gross), "paygw": S(run.total_payg + run.total_study_loan), "super_liability": S(sum((e["this_pay"]["super_liability"] and Decimal(e["this_pay"]["super_liability"]) for e in emps), Z))},
            "notice": "Generated by AccFino for review. Not lodged with the ATO."}


def prepare_pay_event(db, ctx, access, run_id: int) -> PayStpEvent:
    access.require("stp_manage")
    run = db.query(PayRun).filter_by(id=run_id, org_id=ctx.org.id).first()
    if run is None:
        raise NotFound("Pay run")
    if run.status not in ("finalised", "paid"):
        raise Conflict(f"An STP pay event can only be prepared from a finalised pay run (this one is {run.status})", "bad_state")
    prior = db.query(PayStpEvent).filter_by(org_id=ctx.org.id, run_id=run.id).count()
    ev = PayStpEvent(org_id=ctx.org.id, event_type="pay_event" if not prior else "update_event", run_id=run.id, fy=runbuild.fy_label(run.pay_date, ctx.org.fy_end_month or 6),
                     payload=pay_event_payload(db, ctx, run, "pay_event" if not prior else "update_event"), created_by=ctx.user_id)
    if not ev.payload["employer"]["abn"]:
        raise PayrollError("The employer ABN is missing: set it in Payroll > Settings before preparing STP reports")
    db.add(ev)
    db.flush()
    audit.record(db, ctx, "stp.prepare", "stp", ev.id, run.run_no, f"{ev.event_type} prepared for {len(ev.payload['employees'])} employees")
    return ev


def mock_submit(db, ctx, access, event_id: int) -> PayStpEvent:
    access.require("stp_manage")
    ev = db.query(PayStpEvent).filter_by(id=event_id, org_id=ctx.org.id).first()
    if ev is None:
        raise NotFound("STP event")
    if ev.status == "mock_submitted":
        raise Conflict("This STP event was already (mock) submitted", "already_submitted")
    ev.status, ev.submitted_at, ev.mock_reference = "mock_submitted", datetime.utcnow(), f"MOCK-NOT-LODGED-{uuid.uuid4().hex[:8].upper()}"
    audit.record(db, ctx, "stp.mock_submit", "stp", ev.id, ev.mock_reference, "Mock submission recorded (NOT lodged with the ATO)")
    return ev


def ser(ev: PayStpEvent, full=False) -> dict:
    out = {"id": ev.id, "event_type": ev.event_type, "run_id": ev.run_id, "fy": ev.fy, "status": ev.status, "mock_reference": ev.mock_reference,
           "created_at": ev.created_at.isoformat() if ev.created_at else None, "submitted_at": ev.submitted_at.isoformat() if ev.submitted_at else None,
           "employees": len(ev.payload.get("employees", [])), "gross": ev.payload.get("totals", {}).get("gross")}
    if full:
        out["payload"] = ev.payload
    return out


def list_events(db, ctx, access) -> list:
    access.require("stp_manage")
    return [ser(e) for e in db.query(PayStpEvent).filter_by(org_id=ctx.org.id).order_by(PayStpEvent.id.desc()).limit(200)]


def fy_bounds(fy: str, fym: int = 6):
    try:
        y = int(fy[:4])
        assert fy[4] == "-" and int(fy[5:]) == (y + 1) % 100
    except (ValueError, IndexError, AssertionError):
        raise PayrollError("Financial year must look like 2026-27")
    start = date(y, fym % 12 + 1, 1)
    end = date(y + 1, fym % 12 + 1, 1) if fym != 12 else date(y + 1, 1, 1)
    return start, end


def fy_totals(db, ctx, fy: str) -> dict:
    fym = ctx.org.fy_end_month or 6
    start, nxt = fy_bounds(fy, fym)
    agg = {}
    for r, run in (db.query(PayRunEmployee, PayRun).join(PayRun, PayRun.id == PayRunEmployee.run_id)
                   .filter(PayRun.org_id == ctx.org.id, PayRun.status.in_(("finalised", "paid")), PayRun.pay_date >= start, PayRun.pay_date < nxt, PayRunEmployee.status == "included")):
        a = agg.setdefault(r.employee_id, dict(name=r.employee_name, number=r.employee_number, gross=Z, tax=Z, super_total=Z, resc=Z, taxable=Z))
        a["gross"] += r.gross; a["tax"] += r.payg + r.study_loan; a["super_total"] += r.super_total; a["resc"] += r.sacrifice_super; a["taxable"] += r.taxable
    return agg


def finalisation_status(db, ctx, access, fy: str) -> dict:
    access.require("stp_manage")
    fym = ctx.org.fy_end_month or 6
    start, nxt = fy_bounds(fy, fym)
    done = {f.employee_id for f in db.query(PayStpFinalisation).filter_by(org_id=ctx.org.id, fy=fy)}
    open_runs = db.query(PayRun).filter(PayRun.org_id == ctx.org.id, PayRun.pay_date >= start, PayRun.pay_date < nxt, PayRun.status.in_(("draft", "review", "approved"))).count()
    emps = [{"employee_id": i, "employee_number": a["number"], "name": a["name"], "gross": S(a["gross"]), "tax": S(a["tax"]), "super": S(a["super_total"]), "finalised": i in done} for i, a in
            sorted(fy_totals(db, ctx, fy).items(), key=lambda kv: kv[1]["number"])]
    due = date(nxt.year, 7, 14) if fym == 6 else None
    return {"fy": fy, "employees": emps, "open_runs": open_runs, "fy_ended": date.today() >= nxt, "due_date": due.isoformat() if due else None}


def finalise_employees(db, ctx, access, fy: str, employee_ids: list) -> list:
    access.require("stp_manage")
    st = finalisation_status(db, ctx, access, fy)
    if st["open_runs"]:
        raise PayrollError(f"{st['open_runs']} pay run(s) in {fy} are not finalised yet: finalise or cancel them first")
    if not st["fy_ended"]:
        raise PayrollError(f"Financial year {fy} has not ended yet: employees can only be finalised after 30 June (or when they leave and are paid in full)")
    totals = fy_totals(db, ctx, fy)
    out = []
    for i in employee_ids:
        a = totals.get(int(i))
        if a is None:
            raise PayrollError(f"Employee {i} has no pay in {fy}")
        if db.query(PayStpFinalisation.id).filter_by(org_id=ctx.org.id, employee_id=int(i), fy=fy).first():
            raise Conflict(f"{a['name']} is already finalised for {fy}", "already_finalised")
        db.add(PayStpFinalisation(org_id=ctx.org.id, employee_id=int(i), fy=fy, gross=a["gross"], tax=a["tax"], super_total=a["super_total"], finalised_by=ctx.user_id))
        out.append(a["name"])
    db.flush()
    db.add(PayStpEvent(org_id=ctx.org.id, event_type="finalisation", fy=fy, status="draft", created_by=ctx.user_id,
                       payload={"event_type": "finalisation", "fy": fy, "employer": _employer(db, ctx), "employees": [{"payee_ref": totals[int(i)]["number"], "name": totals[int(i)]["name"], "gross": S(totals[int(i)]["gross"]),
                                                                                                                      "paygw": S(totals[int(i)]["tax"]), "resc": S(totals[int(i)]["resc"])} for i in employee_ids],
                                "notice": "Generated by AccFino for review. Not lodged with the ATO."}))
    audit.record(db, ctx, "stp.finalise", "stp", None, fy, f"{len(out)} employees finalised for {fy}: {', '.join(out)}")
    return out


def payment_summary(db, ctx, access, employee_id: int, fy: str) -> dict:
    access.require("stp_manage")
    e = db.query(PayEmployee).filter_by(id=employee_id, org_id=ctx.org.id).first()
    if e is None:
        raise NotFound("Employee")
    a = fy_totals(db, ctx, fy).get(e.id)
    if a is None:
        raise PayrollError(f"{e.first_name} {e.last_name} has no pay in {fy}")
    return {"fy": fy, "employer": _employer(db, ctx), "employee": f"{e.first_name} {e.last_name}", "employee_number": e.employee_number, "gross_payments": S(a["gross"]), "tax_withheld": S(a["tax"]),
            "reportable_employer_super": S(a["resc"]), "note": "Payment summary data for historical/reference use. Employees normally see this through myGov once finalised via STP."}
